import { Link } from "expo-router";
import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { colors, spacing } from "../../lib/theme";
import { useAuth } from "../../providers/auth-provider";

export default function ForgotPasswordScreen() {
  const { requestPasswordReset } = useAuth(); const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  async function submit() { setError(""); setMessage(""); if (!email.trim()) return setError("Enter your email address."); setSubmitting(true); try { await requestPasswordReset(email); setMessage("If an account exists for that email, a reset link has been sent."); } catch { setError("We could not send the reset email. Check the address and try again."); } finally { setSubmitting(false); } }
  return <View style={styles.container}><Text style={styles.eyebrow}>ACCOUNT RECOVERY</Text><Text style={styles.title}>Reset your password.</Text><Text style={styles.copy}>Enter your account email and we will send instructions to create a new password.</Text><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" onChangeText={setEmail} placeholder="Email address" placeholderTextColor={colors.muted} style={styles.input} value={email} />{error ? <Text style={styles.error}>{error}</Text> : null}{message ? <Text style={styles.message}>{message}</Text> : null}<Pressable disabled={submitting} onPress={submit} style={styles.button}><Text style={styles.buttonText}>{submitting ? "Sending..." : "Send reset link"}</Text></Pressable><Link href="/(auth)/login" style={styles.link}>Back to sign in</Link></View>;
}

const styles = StyleSheet.create({ container: { flex: 1, justifyContent: "center", padding: spacing.xl, backgroundColor: colors.canvas }, eyebrow: { color: colors.brand, fontSize: 12, fontWeight: "700", letterSpacing: 2 }, title: { color: colors.ink, fontSize: 34, fontWeight: "800", lineHeight: 40, marginTop: spacing.md }, copy: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: spacing.md }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, color: colors.ink, fontSize: 16, marginTop: spacing.lg, padding: spacing.md }, error: { color: colors.danger, marginTop: spacing.sm }, message: { color: colors.brand, marginTop: spacing.sm }, button: { alignItems: "center", backgroundColor: colors.brand, borderRadius: 12, marginTop: spacing.lg, padding: spacing.md }, buttonText: { color: colors.surface, fontSize: 16, fontWeight: "700" }, link: { color: colors.brand, fontSize: 15, fontWeight: "700", marginTop: spacing.lg, textAlign: "center" } });
