"use client";
import { useEffect, useState } from "react";
import { Loading } from "@/components/ui/loading";
import { useAuth } from "@/contexts/auth-context";
import { deleteAdminUser, getAdminUsers, setUserBlocked, type AdminUser, type Meta } from "@/lib/admin-api";
import { dialog, toast } from "@/lib/notifications";
export default function UsersPage() {
  const { firebaseUser } = useAuth(); const [users, setUsers] = useState<AdminUser[]>([]); const [meta, setMeta] = useState<Meta|null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  useEffect(() => { if (!firebaseUser) return; setLoading(true); firebaseUser.getIdToken().then((token) => getAdminUsers(token, { page, limit: 15, search, status })).then((result) => { setUsers(result.data); setMeta(result.meta); }).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, [firebaseUser, page, reload, search, status]);
  const toggle = async (user: AdminUser) => { if (!firebaseUser) return; await setUserBlocked(await firebaseUser.getIdToken(), user.id, user.status !== "BLOCKED"); toast.success(user.status === "BLOCKED" ? "User unblocked." : "User blocked."); setReload((v) => v + 1); };
  const remove = async (user: AdminUser) => { if (!firebaseUser || !(await dialog.confirm("Delete user?", user.email)).isConfirmed) return; await deleteAdminUser(await firebaseUser.getIdToken(), user.id); toast.success("User deleted."); setReload((v) => v + 1); };
  return <div className="mx-auto max-w-[1440px]"><h1 className="text-3xl font-semibold">User Management</h1><div className="mt-5 flex gap-3 rounded-xl border bg-white p-4"><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search name or email" className="h-11 flex-1 rounded-lg border px-3"/><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 rounded-lg border px-3"><option value="">All statuses</option><option>ACTIVE</option><option>BLOCKED</option><option>DELETED</option></select></div>{loading ? <Loading fullScreen={false}/> : <div className="mt-5 overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#f3f4f8]"><tr><th className="p-4">User</th><th>Plan</th><th>Status</th><th>Joined</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-t"><td className="p-4"><p className="font-semibold">{user.name}</p><p className="text-xs text-[#626773]">{user.email}</p></td><td>{user.plan}</td><td><span className="rounded-full bg-[#eef0ff] px-2 py-1 text-xs">{user.status}</span></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td className="p-4 text-right">{user.role !== "ADMIN" && <><button onClick={() => void toggle(user)} className="mr-2 rounded-lg border px-3 py-2 text-xs font-semibold">{user.status === "BLOCKED" ? "Unblock" : "Block"}</button><button onClick={() => void remove(user)} className="rounded-lg px-3 py-2 text-xs font-semibold text-red-700">Delete</button></>}</td></tr>)}</tbody></table></div>}{meta && meta.totalPages > 1 && <div className="mt-4 flex justify-end gap-2"><button disabled={page===1} onClick={() => setPage(page-1)} className="rounded border px-3 py-2">Previous</button><button disabled={page===meta.totalPages} onClick={() => setPage(page+1)} className="rounded border px-3 py-2">Next</button></div>}</div>;
}
