"use client";
import { useEffect, useMemo, useState } from "react";
import { Loading } from "@/components/ui/loading";
import { useAuth } from "@/contexts/auth-context";
import { getAdminPayments, type AdminPayment, type Meta } from "@/lib/admin-api";
import { toast } from "@/lib/notifications";
export default function AdminPaymentsPage() {
  const { firebaseUser } = useAuth(); const [payments, setPayments] = useState<AdminPayment[]>([]); const [meta, setMeta] = useState<Meta|null>(null); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!firebaseUser) return; setLoading(true); firebaseUser.getIdToken().then((token) => getAdminPayments(token, { page, limit: 20, status })).then((result) => { setPayments(result.data); setMeta(result.meta); }).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, [firebaseUser, page, status]);
  const total = useMemo(() => payments.filter((item) => item.status === "SUCCESS").reduce((sum, item) => sum + Number(item.amount), 0), [payments]);
  return <div className="mx-auto max-w-[1440px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">Payments & Subscriptions</h1><p className="mt-1 text-sm text-[#626773]">Monitor checkout and subscription revenue.</p></div><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="h-11 rounded-lg border bg-white px-3"><option value="">All statuses</option><option>PENDING</option><option>SUCCESS</option><option>FAILED</option><option>REFUNDED</option></select></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><Card label="Visible payments" value={meta?.total ?? 0}/><Card label="Successful page revenue" value={`$${total.toFixed(2)}`}/><Card label="Successful payments" value={payments.filter((item) => item.status === "SUCCESS").length}/></div>{loading ? <Loading fullScreen={false}/> : <div className="mt-5 overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#f3f4f8]"><tr><th className="p-4">Customer</th><th>Plan</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id} className="border-t"><td className="p-4"><p className="font-semibold">{payment.user.name}</p><p className="text-xs text-[#626773]">{payment.user.email}</p></td><td>{payment.plan}</td><td>${Number(payment.amount).toFixed(2)} {payment.currency.toUpperCase()}</td><td><span className="rounded-full bg-[#eef0ff] px-2 py-1 text-xs">{payment.status}</span></td><td>{new Date(payment.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}{meta && meta.totalPages > 1 && <div className="mt-4 flex justify-end gap-2"><button disabled={page===1} onClick={() => setPage(page-1)} className="rounded border px-3 py-2">Previous</button><button disabled={page===meta.totalPages} onClick={() => setPage(page+1)} className="rounded border px-3 py-2">Next</button></div>}</div>;
}
function Card({ label, value }: { label: string; value: string|number }) { return <section className="rounded-xl border bg-white p-5"><p className="text-xs font-semibold uppercase text-[#777d88]">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></section>; }
