"use client";
import { useEffect, useMemo, useState } from "react";
import { Loading } from "@/components/ui/loading";
import { AdminBadge, AdminEmpty, AdminPageHeader, AdminPagination, AdminTable, AdminTableHead, adminCard, adminInput } from "@/components/admin/admin-ui";
import { useAuth } from "@/contexts/auth-context";
import { getAdminPayments, type AdminPayment, type Meta } from "@/lib/admin-api";
import { toast } from "@/lib/notifications";
export default function AdminPaymentsPage() {
  const { firebaseUser } = useAuth(); const [payments, setPayments] = useState<AdminPayment[]>([]); const [meta, setMeta] = useState<Meta | null>(null); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!firebaseUser) return; setLoading(true); firebaseUser.getIdToken().then((token) => getAdminPayments(token, { page, limit: 20, status })).then((result) => { setPayments(result.data); setMeta(result.meta); }).catch((error) => toast.error(error.message)).finally(() => setLoading(false)); }, [firebaseUser, page, status]);
  const total = useMemo(() => payments.filter((item) => item.status === "SUCCESS").reduce((sum, item) => sum + Number(item.amount), 0), [payments]);
  return <div className="mx-auto max-w-[1440px] pb-10"><AdminPageHeader title="Payments & subscriptions" description="Monitor checkout outcomes and subscription revenue." action={<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} className={adminInput}><option value="">All statuses</option><option value="PENDING">Pending</option><option value="SUCCESS">Successful</option><option value="FAILED">Failed</option><option value="REFUNDED">Refunded</option></select>}/><div className="mt-6 grid gap-4 sm:grid-cols-3"><Card label="Transactions" value={meta?.total ?? 0}/><Card label="Page revenue" value={`$${total.toFixed(2)}`}/><Card label="Successful" value={payments.filter((item) => item.status === "SUCCESS").length}/></div>{loading ? <Loading fullScreen={false} label="Loading payments"/> : payments.length === 0 ? <AdminEmpty title="No payments found" description="No transactions match this status."/> : <AdminTable><AdminTableHead><th className="px-5 py-4">Customer</th><th className="px-4 py-4">Plan</th><th className="px-4 py-4">Amount</th><th className="px-4 py-4">Status</th><th className="px-5 py-4">Date</th></AdminTableHead><tbody className="divide-y divide-[#edf0f5]">{payments.map((payment) => <tr key={payment.id} className="hover:bg-[#fafaff]"><td className="px-5 py-4"><p className="font-semibold">{payment.user.name}</p><p className="text-xs text-[#747b89]">{payment.user.email}</p></td><td className="px-4 py-4"><AdminBadge tone={payment.plan === "PRO" ? "primary" : payment.plan === "PLUS" ? "warning" : "neutral"}>{payment.plan || "—"}</AdminBadge></td><td className="px-4 py-4 font-semibold">${Number(payment.amount).toFixed(2)} {payment.currency.toUpperCase()}</td><td className="px-4 py-4"><AdminBadge tone={payment.status === "SUCCESS" ? "success" : payment.status === "FAILED" ? "danger" : payment.status === "PENDING" ? "warning" : "neutral"}>{payment.status}</AdminBadge></td><td className="px-5 py-4 text-[#606878]">{new Date(payment.createdAt).toLocaleString()}</td></tr>)}</tbody></AdminTable>}<AdminPagination page={page} totalPages={meta?.totalPages ?? 1} onChange={setPage}/></div>;
}
function Card({ label, value }: { label: string; value: string | number }) { return <section className={`${adminCard} p-5`}><p className="text-xs font-bold uppercase tracking-wide text-[#777d88]">{label}</p><p className="mt-2 text-2xl font-bold text-[#172033]">{value}</p></section>; }
