"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useAuth } from "@/contexts/auth-context";
import { createCategory, deleteCategory, getAdminCategories, updateCategory, type Category } from "@/lib/admin-api";
import { dialog, toast } from "@/lib/notifications";
export default function CategoriesPage() {
  const { firebaseUser } = useAuth(); const [items, setItems] = useState<Category[]>([]); const [editing, setEditing] = useState<Category|null>(null); const [reload, setReload] = useState(0);
  useEffect(() => { if (!firebaseUser) return; firebaseUser.getIdToken().then(getAdminCategories).then(setItems).catch((e) => toast.error(e.message)); }, [firebaseUser, reload]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!firebaseUser) return; const form = new FormData(event.currentTarget); const input = { name: String(form.get("name")).trim(), description: String(form.get("description")).trim() }; const token = await firebaseUser.getIdToken(); if (editing) await updateCategory(token, editing.id, input); else await createCategory(token, input); toast.success(editing ? "Category updated." : "Category created."); setEditing(null); event.currentTarget.reset(); setReload((v) => v + 1); };
  const deactivate = async (item: Category) => { if (!firebaseUser || !(await dialog.confirm("Deactivate category?", item.name)).isConfirmed) return; await deleteCategory(await firebaseUser.getIdToken(), item.id); toast.success("Category deactivated."); setReload((v) => v + 1); };
  return <div className="mx-auto max-w-5xl"><h1 className="text-3xl font-semibold">Category Management</h1><div className="mt-6 grid gap-6 lg:grid-cols-[340px_1fr]"><form onSubmit={save} className="h-fit space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">{editing ? "Edit category" : "New category"}</h2><input name="name" required minLength={2} maxLength={50} defaultValue={editing?.name} placeholder="Category name" className="h-11 w-full rounded-lg border px-3"/><textarea name="description" maxLength={500} defaultValue={editing?.description ?? ""} placeholder="Description" className="w-full rounded-lg border p-3"/><button className="w-full rounded-lg bg-[#5b47ee] py-3 text-sm font-semibold text-white">{editing ? "Save changes" : "Add category"}</button>{editing && <button type="button" onClick={() => setEditing(null)} className="w-full text-sm">Cancel</button>}</form><div className="space-y-3">{items.map((item) => <article key={item.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><div><p className="font-semibold">{item.name}</p><p className="text-xs text-[#626773]">{item._count?.products ?? 0} assets · {item.isActive ? "Active" : "Inactive"}</p></div><div><button onClick={() => setEditing(item)} className="rounded-lg px-3 py-2 text-xs font-semibold text-[#5b47ee]">Edit</button>{item.isActive && <button onClick={() => void deactivate(item)} className="rounded-lg px-3 py-2 text-xs font-semibold text-red-700">Deactivate</button>}</div></article>)}</div></div></div>;
}
