"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useAuth } from "@/contexts/auth-context";
import { createBrand, deleteBrand, getAdminBrands, updateBrand, type Brand } from "@/lib/admin-api";
import { dialog, toast } from "@/lib/notifications";
export default function BrandsPage() {
  const { firebaseUser } = useAuth(); const [items, setItems] = useState<Brand[]>([]); const [editing, setEditing] = useState<Brand|null>(null); const [reload, setReload] = useState(0);
  useEffect(() => { if (!firebaseUser) return; firebaseUser.getIdToken().then(getAdminBrands).then(setItems).catch((e) => toast.error(e.message)); }, [firebaseUser, reload]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!firebaseUser) return; const form = new FormData(event.currentTarget); const input = { name: String(form.get("name")).trim(), description: String(form.get("description")).trim(), websiteUrl: String(form.get("websiteUrl")).trim() || null }; const token = await firebaseUser.getIdToken(); if (editing) await updateBrand(token, editing.id, input); else await createBrand(token, input); toast.success(editing ? "Brand updated." : "Brand created."); setEditing(null); event.currentTarget.reset(); setReload((v) => v + 1); };
  const toggle = async (item: Brand) => { if (!firebaseUser) return; const token = await firebaseUser.getIdToken(); if (item.isActive) { if (!(await dialog.confirm("Deactivate brand?", item.name)).isConfirmed) return; await deleteBrand(token, item.id); } else await updateBrand(token, item.id, { isActive: true }); toast.success(item.isActive ? "Brand deactivated." : "Brand activated."); setReload((v) => v + 1); };
  return <div className="mx-auto max-w-5xl"><h1 className="text-3xl font-semibold">Brand Management</h1><div className="mt-6 grid gap-6 lg:grid-cols-[340px_1fr]"><form onSubmit={save} className="h-fit space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">{editing ? "Edit brand" : "New brand"}</h2><input name="name" required minLength={2} maxLength={80} defaultValue={editing?.name} placeholder="Brand name" className="h-11 w-full rounded-lg border px-3"/><input name="websiteUrl" type="url" defaultValue={editing?.websiteUrl ?? ""} placeholder="Website URL" className="h-11 w-full rounded-lg border px-3"/><textarea name="description" maxLength={500} defaultValue={editing?.description ?? ""} placeholder="Description" className="w-full rounded-lg border p-3"/><button className="w-full rounded-lg bg-[#5b47ee] py-3 text-sm font-semibold text-white">{editing ? "Save changes" : "Add brand"}</button>{editing && <button type="button" onClick={() => setEditing(null)} className="w-full text-sm">Cancel</button>}</form><div className="grid gap-3 sm:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between"><div><p className="font-semibold">{item.name}</p><p className="text-xs text-[#626773]">{item.isActive ? "Active" : "Inactive"}</p></div><span className={`h-2 w-2 rounded-full ${item.isActive ? "bg-green-500" : "bg-gray-400"}`}/></div><p className="mt-3 line-clamp-2 text-xs text-[#626773]">{item.description || "No description"}</p><div className="mt-4"><button onClick={() => setEditing(item)} className="px-3 py-2 text-xs font-semibold text-[#5b47ee]">Edit</button><button onClick={() => void toggle(item)} className="px-3 py-2 text-xs font-semibold">{item.isActive ? "Deactivate" : "Activate"}</button></div></article>)}</div></div></div>;
}
