"use client";
import { useEffect, useState } from "react";
import { Loading } from "@/components/ui/loading";
import { useAuth } from "@/contexts/auth-context";
import { deleteAdminAsset, getAdminAssets, type AdminAsset, type Meta } from "@/lib/admin-api";
import { dialog, toast } from "@/lib/notifications";
export default function AdminAssetsPage() {
  const { firebaseUser } = useAuth(); const [items, setItems] = useState<AdminAsset[]>([]); const [meta, setMeta] = useState<Meta|null>(null); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  useEffect(() => { if (!firebaseUser) return; setLoading(true); firebaseUser.getIdToken().then((token) => getAdminAssets(token, { page, limit: 16, search })).then((result) => { setItems(result.data); setMeta(result.meta); }).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, [firebaseUser, page, reload, search]);
  const remove = async (asset: AdminAsset) => { if (!firebaseUser || !(await dialog.confirm("Remove asset?", `${asset.name} owned by ${asset.user.email}`)).isConfirmed) return; await deleteAdminAsset(await firebaseUser.getIdToken(), asset.id); toast.success("Asset removed."); setReload((v) => v + 1); };
  return <div className="mx-auto max-w-[1440px]"><h1 className="text-3xl font-semibold">Asset Oversight</h1><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search asset or brand" className="mt-5 h-11 w-full max-w-xl rounded-lg border bg-white px-4"/>{loading ? <Loading fullScreen={false}/> : <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((asset) => <article key={asset.id} className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{asset.name}</h2><p className="text-sm text-[#626773]">{asset.brand} · {asset.category.name}</p></div><span className="h-fit rounded-full bg-[#eef0ff] px-2 py-1 text-[10px] font-semibold">{asset.warrantyStatus}</span></div><div className="mt-4 border-t pt-3 text-xs text-[#626773]"><p>Owner: {asset.user.name}</p><p>{asset.user.email}</p><p className="mt-2">Purchased {new Date(asset.purchaseDate).toLocaleDateString()} · ${Number(asset.purchasePrice).toFixed(2)}</p></div><button onClick={() => void remove(asset)} className="mt-4 rounded-lg px-3 py-2 text-xs font-semibold text-red-700 hover:bg-red-50">Remove asset</button></article>)}</div>}{meta && meta.totalPages > 1 && <div className="mt-5 flex justify-end gap-2"><button disabled={page===1} onClick={() => setPage(page-1)} className="rounded border px-3 py-2">Previous</button><button disabled={page===meta.totalPages} onClick={() => setPage(page+1)} className="rounded border px-3 py-2">Next</button></div>}</div>;
}
