"use client";
import { useEffect, useState } from "react";
import { Eye, Search, Trash2 } from "lucide-react";
import { ActionIconButton } from "@/components/ui/action-icon-button";
import { Loading } from "@/components/ui/loading";
import { AdminBadge, AdminEmpty, AdminModal, AdminPageHeader, AdminPagination, AdminTable, AdminTableHead, adminCard, adminInput } from "@/components/admin/admin-ui";
import { useAuth } from "@/contexts/auth-context";
import { deleteAdminAsset, getAdminAssets, type AdminAsset, type Meta } from "@/lib/admin-api";
import { dialog, toast } from "@/lib/notifications";
import { readQuery, replaceQuery } from "@/lib/url-query";
const tone = (status: string) => status === "ACTIVE" ? "success" : status === "EXPIRING_SOON" ? "warning" : status === "EXPIRED" ? "danger" : "neutral";
export default function AdminAssetsPage() {
  const { firebaseUser } = useAuth();
  const [items, setItems] = useState<AdminAsset[]>([]); const [selected, setSelected] = useState<AdminAsset | null>(null); const [meta, setMeta] = useState<Meta | null>(null);
  const [search, setSearch] = useState(() => readQuery("search")); const [sort, setSort] = useState(() => readQuery("sort", "createdAt:desc")); const [page, setPage] = useState(() => Number(readQuery("page", "1")) || 1); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  useEffect(() => { if (!firebaseUser) return; const timer = setTimeout(() => { const [sortBy, sortOrder] = sort.split(":"); setLoading(true); firebaseUser.getIdToken().then((token) => getAdminAssets(token, { page, limit: 15, search, sortBy, sortOrder })).then((result) => { setItems(result.data); setMeta(result.meta); }).catch((error) => toast.error(error.message)).finally(() => setLoading(false)); }, 250); return () => clearTimeout(timer); }, [firebaseUser, page, reload, search, sort]);
  useEffect(() => replaceQuery({ search, sort, page }), [page, search, sort]);
  const remove = async (asset: AdminAsset) => { if (!firebaseUser || !(await dialog.confirm("Remove this asset?", `${asset.name}, owned by ${asset.user.email}, will be removed.`)).isConfirmed) return; try { await deleteAdminAsset(await firebaseUser.getIdToken(), asset.id); toast.success("Asset removed."); setSelected(null); setReload((value) => value + 1); } catch (error) { toast.error(error instanceof Error ? error.message : "Asset could not be removed."); } };
  return <div className="mx-auto max-w-[1440px] pb-10">
    <AdminPageHeader title="Asset oversight" description="Review customer assets, ownership, warranty status, and catalog usage."/>
    <section className={`${adminCard} mt-6 flex flex-col gap-3 p-4 sm:flex-row`}><label className="relative flex-1"><Search className="absolute left-3 top-3 h-5 w-5 text-[#858b98]"/><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search by asset name or brand" className={`${adminInput} w-full pl-10`}/></label><select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }} className={adminInput}><option value="createdAt:desc">Newest first</option><option value="createdAt:asc">Oldest first</option><option value="name:asc">Name A–Z</option><option value="name:desc">Name Z–A</option><option value="purchasePrice:desc">Highest value</option><option value="purchasePrice:asc">Lowest value</option><option value="expiryDate:asc">Expiring first</option></select></section>
    {loading ? <Loading fullScreen={false} label="Loading assets"/> : items.length === 0 ? <AdminEmpty title="No assets found" description="There are no assets matching this search."/> : <AdminTable><AdminTableHead><th className="px-5 py-4">Asset</th><th className="px-4 py-4">Owner</th><th className="px-4 py-4">Warranty</th><th className="px-4 py-4">Value</th><th className="px-5 py-4 text-right">Actions</th></AdminTableHead><tbody className="divide-y divide-[#edf0f5]">{items.map((asset) => <tr key={asset.id} className="hover:bg-[#fafaff]"><td className="px-5 py-4"><p className="font-semibold text-[#182238]">{asset.name}</p><p className="text-xs text-[#747b89]">{asset.brand} · {asset.category.name}</p></td><td className="px-4 py-4"><p className="font-medium">{asset.user.name}</p><p className="text-xs text-[#747b89]">{asset.user.email}</p></td><td className="px-4 py-4"><AdminBadge tone={tone(asset.warrantyStatus)}>{asset.warrantyStatus.replaceAll("_", " ")}</AdminBadge></td><td className="px-4 py-4 font-medium">${Number(asset.purchasePrice).toFixed(2)}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><ActionIconButton icon={Eye} label="View asset" onClick={() => setSelected(asset)}/><ActionIconButton icon={Trash2} label="Remove asset" tone="danger" onClick={() => void remove(asset)}/></div></td></tr>)}</tbody></AdminTable>}
    <AdminPagination page={page} totalPages={meta?.totalPages ?? 1} onChange={setPage}/>
    <AdminModal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.name ?? "Asset details"} description="Administrative asset record">{selected && <div className="grid gap-3 sm:grid-cols-2">{[["Owner", `${selected.user.name}\n${selected.user.email}`],["Brand", selected.brand],["Category", selected.category.name],["Value", `$${Number(selected.purchasePrice).toFixed(2)}`],["Purchased", new Date(selected.purchaseDate).toLocaleDateString()],["Warranty", selected.warrantyStatus.replaceAll("_", " ")]].map(([label,value]) => <div key={label} className="rounded-xl bg-[#f7f8fc] p-4"><p className="text-xs font-bold uppercase text-[#777e8c]">{label}</p><p className="mt-1 whitespace-pre-line text-sm font-medium">{value}</p></div>)}</div>}</AdminModal>
  </div>;
}
