"use client";
import { useState, type FormEvent } from "react";
import { useAuth } from "@/contexts/auth-context";
import { broadcast } from "@/lib/admin-api";
import { dialog, toast } from "@/lib/notifications";
export default function AdminNotificationsPage() {
  const { firebaseUser } = useAuth(); const [sending, setSending] = useState(false); const [preview, setPreview] = useState({ title: "", message: "" });
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!firebaseUser || !(await dialog.confirm("Broadcast notification?", "This will be delivered to every user.")).isConfirmed) return; setSending(true); try { await broadcast(await firebaseUser.getIdToken(), { ...preview, type: "SYSTEM" }); toast.success("Notification broadcast sent."); setPreview({ title: "", message: "" }); } catch (error) { toast.error(error instanceof Error ? error.message : "Broadcast failed."); } finally { setSending(false); } };
  return <div className="mx-auto max-w-4xl"><h1 className="text-3xl font-semibold">Notification Broadcast</h1><p className="mt-1 text-sm text-[#626773]">Send an important system message to every registered user.</p><div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={submit} className="space-y-4 rounded-xl border bg-white p-5"><label className="block text-sm font-semibold">Title <span className="text-red-600">*</span><input required minLength={3} maxLength={100} value={preview.title} onChange={(e) => setPreview((value) => ({ ...value, title: e.target.value }))} className="mt-2 h-11 w-full rounded-lg border px-3"/></label><label className="block text-sm font-semibold">Message <span className="text-red-600">*</span><textarea required minLength={5} maxLength={1000} rows={7} value={preview.message} onChange={(e) => setPreview((value) => ({ ...value, message: e.target.value }))} className="mt-2 w-full rounded-lg border p-3"/></label><button disabled={sending} className="w-full rounded-lg bg-[#5b47ee] py-3 text-sm font-semibold text-white disabled:opacity-50">{sending ? "Broadcasting…" : "Broadcast to all users"}</button></form><section className="h-fit rounded-xl border bg-[#f8f7ff] p-5"><p className="text-xs font-semibold uppercase text-[#777d88]">User preview</p><div className="mt-4 rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className="mt-1 h-2 w-2 rounded-full bg-[#5b47ee]"/><div><h2 className="font-semibold">{preview.title || "Notification title"}</h2><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-[#626773]">{preview.message || "Your system notification will appear here."}</p><p className="mt-3 text-[10px] text-[#8a8f99]">Just now · System</p></div></div></div></section></div></div>;
}
