"use client";
import { useState, type FormEvent } from "react";
import { BellRing, Send } from "lucide-react";
import { AdminPageHeader, adminCard, adminInput } from "@/components/admin/admin-ui";
import { useAuth } from "@/contexts/auth-context";
import { broadcast } from "@/lib/admin-api";
import { dialog, toast } from "@/lib/notifications";
export default function AdminNotificationsPage() {
  const { firebaseUser } = useAuth(); const [sending, setSending] = useState(false); const [preview, setPreview] = useState({ title: "", message: "" });
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!firebaseUser || !(await dialog.confirm("Send this announcement?", "Every active user will receive it in their notification center.")).isConfirmed) return; setSending(true); try { await broadcast(await firebaseUser.getIdToken(), { ...preview, type: "SYSTEM" }); toast.success("Announcement sent."); setPreview({ title: "", message: "" }); } catch (error) { toast.error(error instanceof Error ? error.message : "Announcement could not be sent."); } finally { setSending(false); } };
  return <div className="mx-auto max-w-5xl pb-10"><AdminPageHeader title="Broadcast center" description="Send concise platform announcements to all active customers."/><div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><form onSubmit={submit} className={`${adminCard} space-y-5 p-6`}><label className="block text-sm font-semibold text-[#2a3345]">Title <span className="text-red-600">*</span><input required minLength={3} maxLength={100} value={preview.title} onChange={(event) => setPreview((value) => ({ ...value, title: event.target.value }))} placeholder="Scheduled maintenance" className={`${adminInput} mt-2 w-full`}/></label><label className="block text-sm font-semibold text-[#2a3345]">Message <span className="text-red-600">*</span><textarea required minLength={5} maxLength={1000} rows={8} value={preview.message} onChange={(event) => setPreview((value) => ({ ...value, message: event.target.value }))} placeholder="Share the important details customers need to know." className="mt-2 w-full rounded-xl border border-[#dfe3ed] p-3 text-sm outline-none focus:border-[#7768f2] focus:ring-4 focus:ring-[#5b47ee]/10"/></label><div className="flex justify-end"><button disabled={sending} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#5b47ee] px-5 text-sm font-semibold text-white shadow-lg shadow-[#5b47ee]/20 disabled:opacity-50"><Send className="h-4 w-4"/>{sending ? "Sending..." : "Send announcement"}</button></div></form><section className={`${adminCard} h-fit p-6`}><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#777d88]">Customer preview</p><div className="mt-5 rounded-2xl bg-[#f6f5ff] p-5"><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#5b47ee] text-white"><BellRing className="h-5 w-5"/></span><div><h2 className="font-semibold text-[#182238]">{preview.title || "Announcement title"}</h2><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-[#656c7b]">{preview.message || "Your announcement preview will appear here."}</p><p className="mt-3 text-[11px] text-[#8a8f99]">Just now · System</p></div></div></div><p className="mt-4 text-xs leading-5 text-[#777d88]">Announcements are stored in each customer&apos;s notification center.</p></section></div></div>;
}
