"use client";
import { useEffect, useState } from "react";
import { Download, FileSpreadsheet } from "lucide-react";
import { AdminPageHeader, adminCard } from "@/components/admin/admin-ui";
import { useAuth } from "@/contexts/auth-context";
import { downloadAdminReport, getAdminActivities, type Activity } from "@/lib/admin-api";
import { toast } from "@/lib/notifications";
const reports = [["admin/users", "User directory", "Users, plans, and account states"], ["admin/revenue", "Revenue report", "Successful payments and total revenue"], ["admin/categories", "Category report", "Catalog usage by category"], ["products", "Asset report", "All customer assets"], ["warranty", "Warranty report", "Coverage and expiry status"], ["payments", "Payment report", "Complete transaction history"]] as const;
export default function AdminReportsPage() {
  const { firebaseUser } = useAuth(); const [activities, setActivities] = useState<Activity[]>([]); const [downloading, setDownloading] = useState("");
  useEffect(() => { if (!firebaseUser) return; firebaseUser.getIdToken().then(getAdminActivities).then(setActivities).catch(() => undefined); }, [firebaseUser]);
  const download = async (report: string, format: "PDF" | "EXCEL") => { if (!firebaseUser) return; const key = report + format; setDownloading(key); try { await downloadAdminReport(await firebaseUser.getIdToken(), report, format); toast.success("Report downloaded."); } catch (error) { toast.error(error instanceof Error ? error.message : "Download failed."); } finally { setDownloading(""); } };
  return <div className="mx-auto max-w-[1200px] pb-10"><AdminPageHeader title="Reports & audit" description="Export operational records and review recent platform activity."/><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{reports.map(([id, title, detail]) => <article key={id} className={`${adminCard} p-5`}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eeecff] text-[#5b47ee]"><FileSpreadsheet className="h-5 w-5"/></span><h2 className="mt-4 font-semibold text-[#182238]">{title}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-[#6d7482]">{detail}</p><div className="mt-4 flex gap-2"><button disabled={Boolean(downloading)} onClick={() => void download(id, "PDF")} className="inline-flex items-center gap-2 rounded-xl bg-[#f2f3f7] px-3 py-2 text-xs font-semibold text-[#4d5667]"><Download className="h-3.5 w-3.5"/>PDF</button><button disabled={Boolean(downloading)} onClick={() => void download(id, "EXCEL")} className="inline-flex items-center gap-2 rounded-xl bg-[#5b47ee] px-3 py-2 text-xs font-semibold text-white"><Download className="h-3.5 w-3.5"/>Excel</button></div></article>)}</div><section className={`${adminCard} mt-7 overflow-hidden`}><h2 className="bg-[#f7f8fc] p-5 font-semibold text-[#182238]">Recent administrator activity</h2>{activities.length ? <div>{activities.map((item) => <div key={item.id} className="flex gap-4 border-t border-[#edf0f5] p-4 first:border-t-0"><span className="mt-1.5 h-2 w-2 rounded-full bg-[#5b47ee]"/><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold text-[#2a3345]">{item.title}</p><time className="text-xs text-[#7c8290]">{new Date(item.createdAt).toLocaleString()}</time></div><p className="mt-1 text-sm text-[#687080]">{item.description || `${item.type} · ${item.entity}`}</p></div></div>)}</div> : <p className="p-10 text-center text-sm text-[#747b89]">No administrator activity has been recorded yet.</p>}</section></div>;
}
