"use client";
import { useEffect, useState } from "react";
import { Loading } from "@/components/ui/loading";
import { useAuth } from "@/contexts/auth-context";
import { claimTransitions } from "@/lib/claims-api";
import { getAdminClaims, updateAdminClaim, type Claim, type ClaimStatus } from "@/lib/admin-api";
import { toast } from "@/lib/notifications";
const labels = (value: string) => value.replaceAll("_", " ");
export default function AdminClaimsPage() {
  const { firebaseUser } = useAuth(); const [claims, setClaims] = useState<Claim[]>([]); const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  useEffect(() => { if (!firebaseUser) return; setLoading(true); firebaseUser.getIdToken().then((token) => getAdminClaims(token, { page: 1, limit: 100, status, search })).then((result) => setClaims(result.data)).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, [firebaseUser, reload, search, status]);
  const transition = async (claim: Claim, next: ClaimStatus) => { if (!firebaseUser) return; const resolution = ["RESOLVED","REJECTED"].includes(next) ? window.prompt("Resolution or reason")?.trim() : undefined; await updateAdminClaim(await firebaseUser.getIdToken(), claim.id, { status: next, ...(resolution ? { resolution } : {}) }); toast.success(`Claim moved to ${labels(next)}.`); setReload((v) => v + 1); };
  return <div className="mx-auto max-w-[1440px]"><h1 className="text-3xl font-semibold">Claim Review</h1><div className="mt-5 flex gap-3"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search claim, title, or asset" className="h-11 flex-1 rounded-lg border bg-white px-3"/><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 rounded-lg border bg-white px-3"><option value="">All statuses</option>{Object.keys(claimTransitions).map((value) => <option key={value}>{value}</option>)}</select></div>{loading ? <Loading fullScreen={false}/> : <div className="mt-5 space-y-4">{claims.map((claim) => <article key={claim.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-semibold text-[#5b47ee]">#{claim.claimNumber}</p><h2 className="mt-1 text-lg font-semibold">{claim.title}</h2><p className="text-sm text-[#626773]">{claim.product.name} · {claim.product.brand}</p></div><span className="h-fit rounded-full bg-[#eef0ff] px-3 py-1 text-xs font-semibold">{labels(claim.status)}</span></div><p className="mt-4 text-sm leading-6 text-[#4f5663]">{claim.issueDescription}</p><div className="mt-4 flex flex-wrap gap-2">{claimTransitions[claim.status].map((next) => <button key={next} onClick={() => void transition(claim, next)} className="rounded-lg border border-[#c9c3ff] bg-[#f7f5ff] px-3 py-2 text-xs font-semibold text-[#4b41e1]">{labels(next)}</button>)}</div></article>)}</div>}</div>;
}
