"use client";
import { useEffect, useState } from "react";
import { Loading } from "@/components/ui/loading";
import { useAuth } from "@/contexts/auth-context";
import { claimStatusLabels, claimStatusStyles } from "@/lib/claim-display";
import { claimStatuses } from "@/lib/claims-api";
import { getAdminClaims, updateAdminClaim, type Claim, type ClaimStatus } from "@/lib/admin-api";
import { toast } from "@/lib/notifications";

export default function AdminClaimsPage() {
  const { firebaseUser } = useAuth(); const [claims, setClaims] = useState<Claim[]>([]); const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  useEffect(() => { if (!firebaseUser) return; setLoading(true); firebaseUser.getIdToken().then((token) => getAdminClaims(token, { page: 1, limit: 100, status, search })).then((result) => setClaims(result.data)).catch((cause) => toast.error(cause.message)).finally(() => setLoading(false)); }, [firebaseUser, reload, search, status]);
  const changeStatus = async (claim: Claim, next: ClaimStatus) => { if (!firebaseUser || next === claim.status) return; try { await updateAdminClaim(await firebaseUser.getIdToken(), claim.id, { status: next }); toast.success("Claim updated."); setReload((value) => value + 1); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Could not update claim."); } };
  return <div className="mx-auto max-w-[1440px]"><h1 className="text-3xl font-semibold">Claims</h1><p className="mt-1 text-sm text-[#626773]">View and manage all customer claims.</p><div className="mt-5 flex gap-3"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search claim or asset" className="h-11 flex-1 rounded-lg border border-[#d7dae4] bg-white px-3"/><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-lg border border-[#d7dae4] bg-white px-3"><option value="">All statuses</option>{claimStatuses.map((value) => <option key={value} value={value}>{claimStatusLabels[value]}</option>)}</select></div>{loading ? <Loading fullScreen={false}/> : <div className="mt-5 overflow-hidden rounded-xl border border-[#dfe2ea] bg-white"><table className="w-full min-w-[850px] text-left"><thead className="bg-[#f6f7fb] text-xs uppercase text-[#687080]"><tr><th className="px-5 py-4">Claim</th><th className="px-4 py-4">Asset</th><th className="px-4 py-4">Issue</th><th className="px-4 py-4">Status</th></tr></thead><tbody className="divide-y divide-[#e8eaf0]">{claims.map((claim) => <tr key={claim.id}><td className="px-5 py-4"><p className="text-sm font-semibold">{claim.title}</p><p className="text-xs text-[#737985]">#{claim.claimNumber}</p></td><td className="px-4 py-4 text-sm">{claim.product.name}</td><td className="max-w-md px-4 py-4 text-sm text-[#555b67]">{claim.issueDescription}</td><td className="px-4 py-4"><select value={claim.status} onChange={(event) => void changeStatus(claim, event.target.value as ClaimStatus)} className={`h-9 rounded-lg border-0 px-3 text-xs font-semibold ${claimStatusStyles[claim.status]}`}>{claimStatuses.map((value) => <option key={value} value={value}>{claimStatusLabels[value]}</option>)}</select></td></tr>)}</tbody></table></div>}</div>;
}
